In [1]:
import sys
import os

# Get the project root directory
project_root = os.path.abspath("..")

# Add project root to Python path
if project_root not in sys.path:
    sys.path.append(project_root)

print("Project root added:", project_root)

Project root added: /home/rakesh/Desktop/AI/NuScenes_dataset

In [2]:
from scripts.scene_extractor import SceneExtractor

In [3]:
extractor = SceneExtractor(
    dataroot="../datasets/nuscenes"
)

======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.363 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======

In [4]:
print(extractor.get_total_scenes())

10

In [5]:
extractor.print_scene_summary()

================================================================================
NuScenes Scene Summary
================================================================================

Scene 1
----------------------------------------
Name : scene-0061
Description : Parked truck, construction, intersection, turn left, following a van
First Sample : ca9a282c9e77460f8360f564131a8af5
Last Sample : ed5fc18c31904f96a8f0dbb99ff069c0

Scene 2
----------------------------------------
Name : scene-0103
Description : Many peds right, wait for turning car, long bike rack left, cyclist
First Sample : 3e8750f331d7499e9b5123e9eb70f2e2
Last Sample : 281b92269fd648d4b52d06ac06ca6d65

Scene 3
----------------------------------------
Name : scene-0553
Description : Wait at intersection, bicycle, large truck, peds crossing crosswalk, ped with stroller
First Sample : 8687ba92abd3406aa797115b874ebeba
Last Sample : dcbe451d383e450786aaad04ab9d3790

Scene 4
----------------------------------------
Name : scene-0655
Description : Parking lot, parked cars, jaywalker, bendy bus, gardening vehicles
First Sample : 5991fad3280c4f84b331536c32001a04
Last Sample : 35833ae5808e4ef186d1fdebac3d9cf6

Scene 5
----------------------------------------
Name : scene-0757
Description : Arrive at busy intersection, bus, wait at intersection, bicycle, peds
First Sample : cd9964f8c3d34383b16e9c2997de1ed0
Last Sample : 8fe9664cec514a58b1184c4fcefda6b5

Scene 6
----------------------------------------
Name : scene-0796
Description : Scooter, peds on sidewalk, bus, cars, truck, fake construction worker, bicycle, cross intersection, car overtaking us
First Sample : c1676a2feac74eee8aa38ca3901787d6
Last Sample : 63c24b51feb94f14bec29022dae4975d

Scene 7
----------------------------------------
Name : scene-0916
Description : Parking lot, bicycle rack, parked bicycles, bus, many peds, parked scooters, parked motorcycle
First Sample : b5989651183643369174912bc5641d3b
Last Sample : b4ff30109dd14c89b24789dc5713cf8c

Scene 8
----------------------------------------
Name : scene-1077
Description : Night, big street, bus stop, high speed, construction vehicle
First Sample : 5998b71b64c146769bde1d5430741381
Last Sample : ee9b3f38dadd40588f43ba590c4751b9

Scene 9
----------------------------------------
Name : scene-1094
Description : Night, after rain, many peds, PMD, ped with bag, jaywalker, truck, scooter
First Sample : e6b0b282aa174a978272dc2d0a89d560
Last Sample : 4e1d1031fe9f45f981a2f598365fc645

Scene 10
----------------------------------------
Name : scene-1100
Description : Night, peds in sidewalk, peds cross crosswalk, scooter, PMD, difficult lighting
First Sample : a480496a5988410fbe3d8ed6c84da996
Last Sample : abf3d91d3c28407e80e3334fe89c03cb

In [6]:
extractor.print_scene_summary()

================================================================================
NuScenes Scene Summary
================================================================================

Scene 1
----------------------------------------
Name : scene-0061
Description : Parked truck, construction, intersection, turn left, following a van
First Sample : ca9a282c9e77460f8360f564131a8af5
Last Sample : ed5fc18c31904f96a8f0dbb99ff069c0

Scene 2
----------------------------------------
Name : scene-0103
Description : Many peds right, wait for turning car, long bike rack left, cyclist
First Sample : 3e8750f331d7499e9b5123e9eb70f2e2
Last Sample : 281b92269fd648d4b52d06ac06ca6d65

Scene 3
----------------------------------------
Name : scene-0553
Description : Wait at intersection, bicycle, large truck, peds crossing crosswalk, ped with stroller
First Sample : 8687ba92abd3406aa797115b874ebeba
Last Sample : dcbe451d383e450786aaad04ab9d3790

Scene 4
----------------------------------------
Name : scene-0655
Description : Parking lot, parked cars, jaywalker, bendy bus, gardening vehicles
First Sample : 5991fad3280c4f84b331536c32001a04
Last Sample : 35833ae5808e4ef186d1fdebac3d9cf6

Scene 5
----------------------------------------
Name : scene-0757
Description : Arrive at busy intersection, bus, wait at intersection, bicycle, peds
First Sample : cd9964f8c3d34383b16e9c2997de1ed0
Last Sample : 8fe9664cec514a58b1184c4fcefda6b5

Scene 6
----------------------------------------
Name : scene-0796
Description : Scooter, peds on sidewalk, bus, cars, truck, fake construction worker, bicycle, cross intersection, car overtaking us
First Sample : c1676a2feac74eee8aa38ca3901787d6
Last Sample : 63c24b51feb94f14bec29022dae4975d

Scene 7
----------------------------------------
Name : scene-0916
Description : Parking lot, bicycle rack, parked bicycles, bus, many peds, parked scooters, parked motorcycle
First Sample : b5989651183643369174912bc5641d3b
Last Sample : b4ff30109dd14c89b24789dc5713cf8c

Scene 8
----------------------------------------
Name : scene-1077
Description : Night, big street, bus stop, high speed, construction vehicle
First Sample : 5998b71b64c146769bde1d5430741381
Last Sample : ee9b3f38dadd40588f43ba590c4751b9

Scene 9
----------------------------------------
Name : scene-1094
Description : Night, after rain, many peds, PMD, ped with bag, jaywalker, truck, scooter
First Sample : e6b0b282aa174a978272dc2d0a89d560
Last Sample : 4e1d1031fe9f45f981a2f598365fc645

Scene 10
----------------------------------------
Name : scene-1100
Description : Night, peds in sidewalk, peds cross crosswalk, scooter, PMD, difficult lighting
First Sample : a480496a5988410fbe3d8ed6c84da996
Last Sample : abf3d91d3c28407e80e3334fe89c03cb

In [7]:
extractor.save_scenes_to_csv(
    output_path="../outputs/scene_metadata.csv"
)

Scene data saved to: ../outputs/scene_metadata.csv

In [8]:
print(hasattr(extractor, "save_scenes_to_csv"))

True

In [9]:
from scripts.sample_extractor import SampleExtractor

In [10]:
sample_extractor = SampleExtractor(extractor.nusc)

In [11]:
first_scene = extractor.get_scene(0)

scene_token = first_scene["token"]

print("Scene Name:", first_scene["name"])
print("Scene Token:", scene_token)

Scene Name: scene-0061
Scene Token: cc8c0bf57f984915a77078b10eb33198

In [12]:
count = sample_extractor.get_sample_count(scene_token)

print("Total Samples in Scene:", count)

Total Samples in Scene: 39

In [13]:
sample_extractor.print_sample_summary(scene_token)

================================================================================
Sample Summary for Scene: cc8c0bf57f984915a77078b10eb33198
================================================================================
Total Samples: 39

Sample 1
----------------------------------------
Token: ca9a282c9e77460f8360f564131a8af5
Timestamp: 1532402927647951
Next: 39586f9d59004284a7114a68825e8eec
Previous:

Sample 2
----------------------------------------
Token: 39586f9d59004284a7114a68825e8eec
Timestamp: 1532402928147847
Next: 356d81f38dd9473ba590f39e266f54e5
Previous: ca9a282c9e77460f8360f564131a8af5

Sample 3
----------------------------------------
Token: 356d81f38dd9473ba590f39e266f54e5
Timestamp: 1532402928698048
Next: e0845f5322254dafadbbed75aaa07969
Previous: 39586f9d59004284a7114a68825e8eec

Sample 4
----------------------------------------
Token: e0845f5322254dafadbbed75aaa07969
Timestamp: 1532402929197353
Next: c923fe08b2ff4e27975d2bf30934383b
Previous: 356d81f38dd9473ba590f39e266f54e5

Sample 5
----------------------------------------
Token: c923fe08b2ff4e27975d2bf30934383b
Timestamp: 1532402929697797
Next: f1e3d9d08f044c439ce86a2d6fcca57b
Previous: e0845f5322254dafadbbed75aaa07969

In [14]:
from scripts.image_extractor import ImageExtractor

In [15]:
image_extractor = ImageExtractor(extractor.nusc)

In [16]:
first_scene = extractor.get_scene(0)

scene_token = first_scene["token"]

samples = sample_extractor.get_samples_in_scene(scene_token)

first_sample = samples[0]

In [17]:
image_extractor.print_image_summary(first_sample)

================================================================================
Image Summary
================================================================================
CAM_FRONT:
  ../datasets/nuscenes/samples/CAM_FRONT/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402927612460.jpg
CAM_FRONT_LEFT:
  ../datasets/nuscenes/samples/CAM_FRONT_LEFT/n015-2018-07-24-11-22-45+0800__CAM_FRONT_LEFT__1532402927604844.jpg
CAM_FRONT_RIGHT:
  ../datasets/nuscenes/samples/CAM_FRONT_RIGHT/n015-2018-07-24-11-22-45+0800__CAM_FRONT_RIGHT__1532402927620339.jpg
CAM_BACK:
  ../datasets/nuscenes/samples/CAM_BACK/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg
CAM_BACK_LEFT:
  ../datasets/nuscenes/samples/CAM_BACK_LEFT/n015-2018-07-24-11-22-45+0800__CAM_BACK_LEFT__1532402927647423.jpg
CAM_BACK_RIGHT:
  ../datasets/nuscenes/samples/CAM_BACK_RIGHT/n015-2018-07-24-11-22-45+0800__CAM_BACK_RIGHT__1532402927627893.jpg

In [18]:
image_extractor.print_image_summary(first_sample)

================================================================================
Image Summary
================================================================================
CAM_FRONT:
  ../datasets/nuscenes/samples/CAM_FRONT/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402927612460.jpg
CAM_FRONT_LEFT:
  ../datasets/nuscenes/samples/CAM_FRONT_LEFT/n015-2018-07-24-11-22-45+0800__CAM_FRONT_LEFT__1532402927604844.jpg
CAM_FRONT_RIGHT:
  ../datasets/nuscenes/samples/CAM_FRONT_RIGHT/n015-2018-07-24-11-22-45+0800__CAM_FRONT_RIGHT__1532402927620339.jpg
CAM_BACK:
  ../datasets/nuscenes/samples/CAM_BACK/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg
CAM_BACK_LEFT:
  ../datasets/nuscenes/samples/CAM_BACK_LEFT/n015-2018-07-24-11-22-45+0800__CAM_BACK_LEFT__1532402927647423.jpg
CAM_BACK_RIGHT:
  ../datasets/nuscenes/samples/CAM_BACK_RIGHT/n015-2018-07-24-11-22-45+0800__CAM_BACK_RIGHT__1532402927627893.jpg

In [19]:
from scripts.lidar_extractor import LiDARExtractor

In [20]:
lidar_extractor = LiDARExtractor(extractor.nusc)

In [21]:
lidar_extractor.print_lidar_summary(first_sample)

================================================================================
LiDAR Summary
================================================================================
LiDAR Path:
../datasets/nuscenes/samples/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin

In [22]:
lidar_extractor.print_lidar_summary(first_sample)

================================================================================
LiDAR Summary
================================================================================
LiDAR Path:
../datasets/nuscenes/samples/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin

In [23]:
from scripts.annotation_extractor import AnnotationExtractor

In [24]:
annotation_extractor = AnnotationExtractor(extractor.nusc)

In [25]:
annotation_extractor.print_annotation_summary(first_sample)

================================================================================
Annotation Summary
================================================================================
Total Objects: 69

Object 1
----------------------------------------
Annotation Token: ef63a697930c4b20a6b9791f423351da
Instance Token: 6dd2cbf4c24b4caeb625035869bca7b5
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [373.256, 1130.419, 0.8]
Size: [0.621, 0.669, 1.642]
LiDAR Points: 1

Object 2
----------------------------------------
Annotation Token: 6b89da9bf1f84fd6a5fbe1c3b236f809
Instance Token: 48d58b69b40149aeb2e64aa4b1a9192f
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [378.888, 1153.348, 0.865]
Size: [0.775, 0.769, 1.711]
LiDAR Points: 2

Object 3
----------------------------------------
Annotation Token: 924ee6ac1fed440a9d9e3720aac635a0
Instance Token: bd26c2cdb22d4bb1834e808c89128898
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: vehicle.car
Position: [353.794, 1132.355, 0.602]
Size: [2.011, 4.633, 1.573]
LiDAR Points: 5

Object 4
----------------------------------------
Annotation Token: 91e3608f55174a319246f361690906ba
Instance Token: 6e04e175f20d402f8cbbdf701fe99d92
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [376.13, 1158.507, 0.938]
Size: [0.752, 0.819, 1.637]
LiDAR Points: 1

Object 5
----------------------------------------
Annotation Token: cd051723ed9c40f692b9266359f547af
Instance Token: 4a5a657f59914516bade8551072e5ab0
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: movable_object.trafficcone
Position: [410.066, 1196.767, 0.656]
Size: [0.427, 0.359, 0.794]
LiDAR Points: 1

In [26]:
annotation_extractor.print_annotation_summary(first_sample)

================================================================================
Annotation Summary
================================================================================
Total Objects: 69

Object 1
----------------------------------------
Annotation Token: ef63a697930c4b20a6b9791f423351da
Instance Token: 6dd2cbf4c24b4caeb625035869bca7b5
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [373.256, 1130.419, 0.8]
Size: [0.621, 0.669, 1.642]
LiDAR Points: 1

Object 2
----------------------------------------
Annotation Token: 6b89da9bf1f84fd6a5fbe1c3b236f809
Instance Token: 48d58b69b40149aeb2e64aa4b1a9192f
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [378.888, 1153.348, 0.865]
Size: [0.775, 0.769, 1.711]
LiDAR Points: 2

Object 3
----------------------------------------
Annotation Token: 924ee6ac1fed440a9d9e3720aac635a0
Instance Token: bd26c2cdb22d4bb1834e808c89128898
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: vehicle.car
Position: [353.794, 1132.355, 0.602]
Size: [2.011, 4.633, 1.573]
LiDAR Points: 5

Object 4
----------------------------------------
Annotation Token: 91e3608f55174a319246f361690906ba
Instance Token: 6e04e175f20d402f8cbbdf701fe99d92
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: human.pedestrian.adult
Position: [376.13, 1158.507, 0.938]
Size: [0.752, 0.819, 1.637]
LiDAR Points: 1

Object 5
----------------------------------------
Annotation Token: cd051723ed9c40f692b9266359f547af
Instance Token: 4a5a657f59914516bade8551072e5ab0
Sample Token: ca9a282c9e77460f8360f564131a8af5
Category: movable_object.trafficcone
Position: [410.066, 1196.767, 0.656]
Size: [0.427, 0.359, 0.794]
LiDAR Points: 1

In [27]:
from scripts.database_writer import DatabaseWriter

In [28]:
db_writer = DatabaseWriter(output_dir="../outputs")

In [29]:
first_scene = extractor.get_scene(0)

scene_token = first_scene["token"]

samples = sample_extractor.get_samples_in_scene(scene_token)

print("Number of samples:", len(samples))

Number of samples: 39

In [30]:
db_writer.save_sample_metadata(samples)

Sample metadata saved to: ../outputs/sample_metadata.csv

In [31]:
db_writer.save_image_metadata(samples, image_extractor)

Image metadata saved to: ../outputs/image_metadata.csv

In [32]:
db_writer.save_lidar_metadata(samples, lidar_extractor)

LiDAR metadata saved to: ../outputs/lidar_metadata.csv

In [33]:
db_writer.save_annotation_metadata(samples, annotation_extractor)

KeyError: 'token'

In [ ]:
from scripts.category_filter import CategoryFilter

In [ ]:
category_filter = CategoryFilter()

In [ ]:
filtered_df = category_filter.filter_by_category(
    category="vehicle.car"
)

============================================================
Category Filtering Summary
============================================================
Target Category : vehicle.car
Total Annotations : 4699
Filtered Objects : 348
Output File : ../outputs/filtered_vehicle_annotations.csv
============================================================

In [ ]:
filtered_df.head()

,sample_token,annotation_token,category,translation,size,num_lidar_pts,num_radar_pts
2,ca9a282c9e77460f8360f564131a8af5,924ee6ac1fed440a9d9e3720aac635a0,vehicle.car,"[353.794, 1132.355, 0.602]","[2.011, 4.633, 1.573]",5,0
7,ca9a282c9e77460f8360f564131a8af5,63b89fe17f3e41ecbe28337e0e35db8e,vehicle.car,"[409.132, 1201.516, 1.01]","[1.837, 4.32, 1.631]",45,6
16,ca9a282c9e77460f8360f564131a8af5,16140fbf143d4e26a4a7613cbd3aa0e8,vehicle.car,"[393.357, 1149.173, 0.741]","[1.708, 4.01, 1.631]",4,2
19,ca9a282c9e77460f8360f564131a8af5,74986f1604f047b6925d409915265bf7,vehicle.car,"[392.077, 1104.169, 1.034]","[2.135, 4.956, 2.17]",1,0
36,ca9a282c9e77460f8360f564131a8af5,cda0a9085607438c9b1ea87f4360dd64,vehicle.car,"[394.039, 1143.246, 0.615]","[1.847, 4.115, 1.526]",5,1

In [ ]:
from scripts.dataset_statistics import DatasetStatistics

In [ ]:
statistics_generator = DatasetStatistics()

In [ ]:
stats = statistics_generator.generate_statistics()

============================================================
Dataset Statistics
============================================================
Total Objects : 4699

                                Category  Count  Percentage
0                 movable_object.barrier   1540       32.77
1                 human.pedestrian.adult   1229       26.15
2             movable_object.trafficcone   1003       21.34
3                            vehicle.car    348        7.41
4   human.pedestrian.construction_worker    164        3.49
5                          vehicle.truck    157        3.34
6                        vehicle.bicycle     68        1.45
7                   vehicle.construction     64        1.36
8                     vehicle.motorcycle     59        1.26
9                      vehicle.bus.rigid     32        0.68
10      movable_object.pushable_pullable     22        0.47
11                 movable_object.debris     13        0.28
============================================================
Statistics saved to : ../outputs/dataset_statistics.csv
============================================================

In [ ]:
from scripts.image_annotation_linker import ImageAnnotationLinker

In [ ]:
linker = ImageAnnotationLinker()

In [ ]:
linked_df = linker.link_annotations_to_images()

============================================================
Image Annotation Linking Summary
============================================================
Annotations : 4699
Images      : 234
Linked Rows : 28194
============================================================
Saved to : ../outputs/linked_image_annotations.csv
============================================================

In [ ]:
linked_df.head()

,sample_token,annotation_token,category,translation,size,num_lidar_pts,num_radar_pts,camera_channel,image_path
0,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0,CAM_FRONT,../datasets/nuscenes/samples/CAM_FRONT/n015-20...
1,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0,CAM_FRONT_LEFT,../datasets/nuscenes/samples/CAM_FRONT_LEFT/n0...
2,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0,CAM_FRONT_RIGHT,../datasets/nuscenes/samples/CAM_FRONT_RIGHT/n...
3,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0,CAM_BACK,../datasets/nuscenes/samples/CAM_BACK/n015-201...
4,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0,CAM_BACK_LEFT,../datasets/nuscenes/samples/CAM_BACK_LEFT/n01...

In [ ]:
import pandas as pd

annotation_df = pd.read_csv(
    "../outputs/annotation_metadata.csv"
)

annotation_df.head()

,sample_token,annotation_token,category,translation,size,num_lidar_pts,num_radar_pts
0,ca9a282c9e77460f8360f564131a8af5,ef63a697930c4b20a6b9791f423351da,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]",1,0
1,ca9a282c9e77460f8360f564131a8af5,6b89da9bf1f84fd6a5fbe1c3b236f809,human.pedestrian.adult,"[378.888, 1153.348, 0.865]","[0.775, 0.769, 1.711]",2,0
2,ca9a282c9e77460f8360f564131a8af5,924ee6ac1fed440a9d9e3720aac635a0,vehicle.car,"[353.794, 1132.355, 0.602]","[2.011, 4.633, 1.573]",5,0
3,ca9a282c9e77460f8360f564131a8af5,91e3608f55174a319246f361690906ba,human.pedestrian.adult,"[376.13, 1158.507, 0.938]","[0.752, 0.819, 1.637]",1,0
4,ca9a282c9e77460f8360f564131a8af5,cd051723ed9c40f692b9266359f547af,movable_object.trafficcone,"[410.066, 1196.767, 0.656]","[0.427, 0.359, 0.794]",1,0

In [ ]:
annotation_df.columns

Index(['sample_token', 'annotation_token', 'category', 'translation', 'size',
       'num_lidar_pts', 'num_radar_pts'],
      dtype='object')

In [ ]:
sample_token = annotation_df["sample_token"].iloc[0]

sample = nusc.get("sample", sample_token)

annotation_token = sample["anns"][0]

annotation = nusc.get(
    "sample_annotation",
    annotation_token
)

annotation

NameError: name 'annotation_df' is not defined

In [ ]:
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(
    version='v1.0-mini',
    dataroot='../datasets/nuscenes',
    verbose=True
)

======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.451 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======

In [ ]:
sample_token = annotation_df["sample_token"].iloc[0]

sample = nusc.get("sample", sample_token)

annotation_token = sample["anns"][0]

annotation = nusc.get(
    "sample_annotation",
    annotation_token
)

annotation

{'token': 'ef63a697930c4b20a6b9791f423351da',
 'sample_token': 'ca9a282c9e77460f8360f564131a8af5',
 'instance_token': '6dd2cbf4c24b4caeb625035869bca7b5',
 'visibility_token': '1',
 'attribute_tokens': ['4d8821270b4a47e3a8a300cbec48188e'],
 'translation': [373.256, 1130.419, 0.8],
 'size': [0.621, 0.669, 1.642],
 'rotation': [0.9831098797903927, 0.0, 0.0, -0.18301629506281616],
 'prev': '',
 'next': '7987617983634b119e383d8a29607fd7',
 'num_lidar_pts': 1,
 'num_radar_pts': 0,
 'category_name': 'human.pedestrian.adult'}

In [ ]:
import importlib
import scripts.annotation_extractor as annotation_module

importlib.reload(annotation_module)

In [ ]:
from scripts.annotation_extractor import AnnotationExtractor

annotation_extractor = AnnotationExtractor(nusc)

NameError: name 'nusc' is not defined

In [ ]:
annotations = annotation_extractor.get_annotations(
    first_sample
)

annotations[0]

{'annotation_token': 'ef63a697930c4b20a6b9791f423351da',
 'instance_token': '6dd2cbf4c24b4caeb625035869bca7b5',
 'sample_token': 'ca9a282c9e77460f8360f564131a8af5',
 'category': 'human.pedestrian.adult',
 'translation': [373.256, 1130.419, 0.8],
 'size': [0.621, 0.669, 1.642],
 'rotation': [0.9831098797903927, 0.0, 0.0, -0.18301629506281616],
 'visibility_token': '1',
 'attribute_tokens': ['4d8821270b4a47e3a8a300cbec48188e'],
 'prev': '',
 'next': '7987617983634b119e383d8a29607fd7',
 'num_lidar_pts': 1,
 'num_radar_pts': 0}

In [ ]:
import pandas as pd

annotation_df = pd.read_csv(
    "../outputs/annotation_metadata.csv"
)

In [ ]:
annotation_df.columns

Index(['sample_token', 'annotation_token', 'category', 'translation', 'size',
       'num_lidar_pts', 'num_radar_pts'],
      dtype='object')

In [ ]:
print(
    "Total annotations:",
    len(annotation_df)
)

print(
    "Unique physical instances:",
    annotation_df["instance_token"].nunique()
)

Total annotations: 4699

KeyError: 'instance_token'

In [ ]:
import importlib
import scripts.annotation_extractor as annotation_module

importlib.reload(annotation_module)

In [ ]:
from scripts.annotation_extractor import AnnotationExtractor

annotation_extractor = AnnotationExtractor(nusc)

NameError: name 'nusc' is not defined

In [ ]:
from nuscenes.nuscenes import NuScenes

nusc = NuScenes(
    version="v1.0-mini",
    dataroot="../datasets/nuscenes",
    verbose=True
)

======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.443 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.1 seconds.
======

In [ ]:
from scripts.annotation_extractor import AnnotationExtractor

In [34]:
import importlib
import scripts.annotation_extractor as annotation_module

importlib.reload(annotation_module)

from scripts.annotation_extractor import AnnotationExtractor

In [35]:
annotation_extractor = AnnotationExtractor(nusc)

NameError: name 'nusc' is not defined

In [ ]:
first_sample = nusc.sample[0]

In [ ]:
annotations = annotation_extractor.get_annotations(
    first_sample
)

In [ ]:
annotations[0]

{'annotation_token': 'ef63a697930c4b20a6b9791f423351da',
 'instance_token': '6dd2cbf4c24b4caeb625035869bca7b5',
 'sample_token': 'ca9a282c9e77460f8360f564131a8af5',
 'category': 'human.pedestrian.adult',
 'translation': [373.256, 1130.419, 0.8],
 'size': [0.621, 0.669, 1.642],
 'rotation': [0.9831098797903927, 0.0, 0.0, -0.18301629506281616],
 'visibility_token': '1',
 'attribute_tokens': ['4d8821270b4a47e3a8a300cbec48188e'],
 'prev': '',
 'next': '7987617983634b119e383d8a29607fd7',
 'num_lidar_pts': 1,
 'num_radar_pts': 0}

In [ ]:
import pandas as pd

all_annotations = []

for sample in nusc.sample:

    annotations = annotation_extractor.get_annotations(sample)

    all_annotations.extend(annotations)

annotation_df = pd.DataFrame(all_annotations)

annotation_df.to_csv(
    "../outputs/annotation_metadata.csv",
    index=False
)

print("Annotation CSV generated successfully!")
print("Total annotations:", len(annotation_df))

NameError: name 'nusc' is not defined

In [ ]:
annotation_df.columns

Index(['annotation_token', 'instance_token', 'sample_token', 'category',
       'translation', 'size', 'rotation', 'visibility_token',
       'attribute_tokens', 'prev', 'next', 'num_lidar_pts', 'num_radar_pts'],
      dtype='object')

In [ ]:
print("Total annotations:",
      len(annotation_df))

print("Unique physical instances:",
      annotation_df["instance_token"].nunique())

Total annotations: 18538
Unique physical instances: 911

In [ ]:
instance_token = annotation_df["instance_token"].iloc[0]

one_instance = annotation_df[
    annotation_df["instance_token"] == instance_token
]

one_instance

,annotation_token,instance_token,sample_token,category,translation,size,rotation,visibility_token,attribute_tokens,prev,next,num_lidar_pts,num_radar_pts
0,ef63a697930c4b20a6b9791f423351da,6dd2cbf4c24b4caeb625035869bca7b5,ca9a282c9e77460f8360f564131a8af5,human.pedestrian.adult,"[373.256, 1130.419, 0.8]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],,7987617983634b119e383d8a29607fd7,1,0
69,7987617983634b119e383d8a29607fd7,6dd2cbf4c24b4caeb625035869bca7b5,39586f9d59004284a7114a68825e8eec,human.pedestrian.adult,"[373.256, 1130.419, 0.81]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],ef63a697930c4b20a6b9791f423351da,9acb7dfed3454f72b2874dda3bdacc48,1,0
147,9acb7dfed3454f72b2874dda3bdacc48,6dd2cbf4c24b4caeb625035869bca7b5,356d81f38dd9473ba590f39e266f54e5,human.pedestrian.adult,"[373.256, 1130.419, 0.82]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],7987617983634b119e383d8a29607fd7,74f550e3257c4f52af1102c0d49d37b8,0,0
233,74f550e3257c4f52af1102c0d49d37b8,6dd2cbf4c24b4caeb625035869bca7b5,e0845f5322254dafadbbed75aaa07969,human.pedestrian.adult,"[373.256, 1130.419, 0.83]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],9acb7dfed3454f72b2874dda3bdacc48,060be69422ee4b2a8b239b463b995e92,0,1
327,060be69422ee4b2a8b239b463b995e92,6dd2cbf4c24b4caeb625035869bca7b5,c923fe08b2ff4e27975d2bf30934383b,human.pedestrian.adult,"[373.256, 1130.419, 0.84]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",2,[4d8821270b4a47e3a8a300cbec48188e],74f550e3257c4f52af1102c0d49d37b8,a2b20cdbf1ed4018ac795b8845d5deaa,1,0
430,a2b20cdbf1ed4018ac795b8845d5deaa,6dd2cbf4c24b4caeb625035869bca7b5,f1e3d9d08f044c439ce86a2d6fcca57b,human.pedestrian.adult,"[373.256, 1130.419, 0.792]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],060be69422ee4b2a8b239b463b995e92,05e0ad1194804f548be544f2267c7e74,1,0
533,05e0ad1194804f548be544f2267c7e74,6dd2cbf4c24b4caeb625035869bca7b5,4f545737bf3347fbbc9af60b0be9a963,human.pedestrian.adult,"[373.256, 1130.419, 0.744]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],a2b20cdbf1ed4018ac795b8845d5deaa,d15155fecf2f440c97bb0781777e18d4,0,0
643,d15155fecf2f440c97bb0781777e18d4,6dd2cbf4c24b4caeb625035869bca7b5,7626dde27d604ac28a0240bdd54eba7a,human.pedestrian.adult,"[373.256, 1130.419, 0.695]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],05e0ad1194804f548be544f2267c7e74,4e41d9560dbf46cab1568b8ef6a282f3,1,0
761,4e41d9560dbf46cab1568b8ef6a282f3,6dd2cbf4c24b4caeb625035869bca7b5,be99ffc878b24aca8956bbb4e0f97d0c,human.pedestrian.adult,"[373.256, 1130.419, 0.647]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],d15155fecf2f440c97bb0781777e18d4,1de9ad564050444486eb587360cf135f,0,0
881,1de9ad564050444486eb587360cf135f,6dd2cbf4c24b4caeb625035869bca7b5,9813c23a5f1448b09bb7910fea9baf20,human.pedestrian.adult,"[373.256, 1130.419, 0.599]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],4e41d9560dbf46cab1568b8ef6a282f3,ed72884bda8a4332bbcb80c285a97929,1,0
1005,ed72884bda8a4332bbcb80c285a97929,6dd2cbf4c24b4caeb625035869bca7b5,023c4df2d451409881d8e6ea82f14704,human.pedestrian.adult,"[373.256, 1130.419, 0.55]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],1de9ad564050444486eb587360cf135f,a72013a0352a496c9a01832f5666ae31,1,0
1132,a72013a0352a496c9a01832f5666ae31,6dd2cbf4c24b4caeb625035869bca7b5,c235638ed66145988d17f9d0601923f2,human.pedestrian.adult,"[373.256, 1130.419, 0.75]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],ed72884bda8a4332bbcb80c285a97929,23f10d5f0d254068941be8797493c7eb,2,0
1261,23f10d5f0d254068941be8797493c7eb,6dd2cbf4c24b4caeb625035869bca7b5,bc3c8a953f6b4dcdb77b521d89f3d9d5,human.pedestrian.adult,"[373.256, 1130.419, 0.95]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],a72013a0352a496c9a01832f5666ae31,b38209aa7b0c49a5b910e7b774b07bd5,3,0
1397,b38209aa7b0c49a5b910e7b774b07bd5,6dd2cbf4c24b4caeb625035869bca7b5,1e3d79dae62742a0ad64c91679863358,human.pedestrian.adult,"[373.256, 1130.419, 1.0]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",3,[4d8821270b4a47e3a8a300cbec48188e],23f10d5f0d254068941be8797493c7eb,a1721876c0944cdd92ebc3c75d55d693,4,0
1534,a1721876c0944cdd92ebc3c75d55d693,6dd2cbf4c24b4caeb625035869bca7b5,2afb9d32310e4546a71cbe432911eca2,human.pedestrian.adult,"[373.256, 1130.419, 1.15]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],b38209aa7b0c49a5b910e7b774b07bd5,70aecbe9b64f4722ab3c230391a3beb8,8,0
1675,70aecbe9b64f4722ab3c230391a3beb8,6dd2cbf4c24b4caeb625035869bca7b5,cd21dbfc3bd749c7b10a5c42562e0c42,human.pedestrian.adult,"[373.214, 1130.48, 1.25]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],a1721876c0944cdd92ebc3c75d55d693,1e8e35d365a441a18dd5503a0ee1c208,5,0
1818,1e8e35d365a441a18dd5503a0ee1c208,6dd2cbf4c24b4caeb625035869bca7b5,88449a5cb1644a199c1c11f6ac034867,human.pedestrian.adult,"[373.183, 1130.419, 1.25]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],70aecbe9b64f4722ab3c230391a3beb8,7fa3a688931b4500b7ce29d187d3b975,9,0
1965,7fa3a688931b4500b7ce29d187d3b975,6dd2cbf4c24b4caeb625035869bca7b5,2ff86dc19c4644a1a88ce5ba848f56e5,human.pedestrian.adult,"[373.152, 1130.357, 1.25]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],1e8e35d365a441a18dd5503a0ee1c208,913072e56d6c4025b9b47ba085dd6d7c,6,0
2113,913072e56d6c4025b9b47ba085dd6d7c,6dd2cbf4c24b4caeb625035869bca7b5,bf2938e43c6f487497cda76b51bfc406,human.pedestrian.adult,"[373.18, 1130.431, 1.263]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],7fa3a688931b4500b7ce29d187d3b975,b8f593154b8144f58e1e53d3c91ab567,7,0
2265,b8f593154b8144f58e1e53d3c91ab567,6dd2cbf4c24b4caeb625035869bca7b5,b26e791522294bec90f86fd72226e35c,human.pedestrian.adult,"[373.208, 1130.504, 1.275]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],913072e56d6c4025b9b47ba085dd6d7c,f503fa3d050f43cca4af2241b674929a,2,0
2421,f503fa3d050f43cca4af2241b674929a,6dd2cbf4c24b4caeb625035869bca7b5,c844bf5a9f2243ff8f4bf2c85fe218ff,human.pedestrian.adult,"[373.237, 1130.577, 1.288]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],b8f593154b8144f58e1e53d3c91ab567,e5fe9ea066254609b48eb073e81ef209,4,0
2575,e5fe9ea066254609b48eb073e81ef209,6dd2cbf4c24b4caeb625035869bca7b5,fedfb3a6cb804635a0f47143f9ca8d6f,human.pedestrian.adult,"[373.245, 1130.6, 1.3]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],f503fa3d050f43cca4af2241b674929a,2b5948828cdb49e3be6be1320381bbbf,4,1
2726,2b5948828cdb49e3be6be1320381bbbf,6dd2cbf4c24b4caeb625035869bca7b5,965f6af5a92449348409029a5f048a38,human.pedestrian.adult,"[373.245, 1130.6, 1.25]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",4,[4d8821270b4a47e3a8a300cbec48188e],e5fe9ea066254609b48eb073e81ef209,17a6843fefcd4b2b811eddbb1ccd708d,4,0
2874,17a6843fefcd4b2b811eddbb1ccd708d,6dd2cbf4c24b4caeb625035869bca7b5,4711bcd34644420da8bc77163431888e,human.pedestrian.adult,"[373.245, 1130.6, 1.2]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],2b5948828cdb49e3be6be1320381bbbf,146b2111cc0c401ca09d96777758d81e,0,0
3018,146b2111cc0c401ca09d96777758d81e,6dd2cbf4c24b4caeb625035869bca7b5,a34fabc7aa674713b71f98ec541eb2d4,human.pedestrian.adult,"[373.245, 1130.6, 1.15]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],17a6843fefcd4b2b811eddbb1ccd708d,a2f1d09320c3454ba3f2347c4b5903a5,0,0
3154,a2f1d09320c3454ba3f2347c4b5903a5,6dd2cbf4c24b4caeb625035869bca7b5,c78067571d104caba7c568a847d56971,human.pedestrian.adult,"[373.245, 1130.6, 1.1]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",3,[4d8821270b4a47e3a8a300cbec48188e],146b2111cc0c401ca09d96777758d81e,807b3e029a6b4e428f6cc82fc26a35a7,0,0
3279,807b3e029a6b4e428f6cc82fc26a35a7,6dd2cbf4c24b4caeb625035869bca7b5,4246e57f018745c9b2bc68feb3d71b58,human.pedestrian.adult,"[373.245, 1130.6, 1.05]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",2,[4d8821270b4a47e3a8a300cbec48188e],a2f1d09320c3454ba3f2347c4b5903a5,f84a0a9fb64e4aab9ccd87e9fbf815e0,0,1
3401,f84a0a9fb64e4aab9ccd87e9fbf815e0,6dd2cbf4c24b4caeb625035869bca7b5,a7acb150914b40bdad9a2dc4e657cbf9,human.pedestrian.adult,"[373.245, 1130.6, 1.0]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],807b3e029a6b4e428f6cc82fc26a35a7,7670ac8bc5044d5a9e11e205c839385d,0,0
3523,7670ac8bc5044d5a9e11e205c839385d,6dd2cbf4c24b4caeb625035869bca7b5,0cd661df01aa40c3bb3a773ba86f753a,human.pedestrian.adult,"[373.245, 1130.6, 0.95]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],f84a0a9fb64e4aab9ccd87e9fbf815e0,163d85048698495dbf55a35f613c5fb9,0,0
3646,163d85048698495dbf55a35f613c5fb9,6dd2cbf4c24b4caeb625035869bca7b5,378a3a3e9af346308ab9dff8ced46d9c,human.pedestrian.adult,"[373.245, 1130.6, 0.9]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],7670ac8bc5044d5a9e11e205c839385d,3a930d1793434d9a8a87d6eba28ff70e,1,0
3771,3a930d1793434d9a8a87d6eba28ff70e,6dd2cbf4c24b4caeb625035869bca7b5,eef55c3b48f34d949959b45130ee293a,human.pedestrian.adult,"[373.258, 1130.608, 0.928]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],163d85048698495dbf55a35f613c5fb9,f7e190375e1f4e569ba16fcdabf6e4b3,0,0
3890,f7e190375e1f4e569ba16fcdabf6e4b3,6dd2cbf4c24b4caeb625035869bca7b5,5fda58ee3ae44ab9b4bbac7a2de66c27,human.pedestrian.adult,"[373.271, 1130.617, 0.956]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],3a930d1793434d9a8a87d6eba28ff70e,6f371d3f0d7d494eaa6f81daa3df58c0,0,0
4006,6f371d3f0d7d494eaa6f81daa3df58c0,6dd2cbf4c24b4caeb625035869bca7b5,919e3c4cec934168a3152077a9adcbea,human.pedestrian.adult,"[373.285, 1130.626, 0.984]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],f7e190375e1f4e569ba16fcdabf6e4b3,90d94112b9ea4fb691e988b40af5b161,0,0
4119,90d94112b9ea4fb691e988b40af5b161,6dd2cbf4c24b4caeb625035869bca7b5,b73152cab88f49d9ba195da81fde1809,human.pedestrian.adult,"[373.298, 1130.635, 1.012]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],6f371d3f0d7d494eaa6f81daa3df58c0,b964464ea45d4e9493f324ba8d2a82a3,0,0
4232,b964464ea45d4e9493f324ba8d2a82a3,6dd2cbf4c24b4caeb625035869bca7b5,6aa6fa91e0d1492e812eb7e57c47df6e,human.pedestrian.adult,"[373.311, 1130.643, 1.039]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],90d94112b9ea4fb691e988b40af5b161,794fcc425f074a1392206ed925fdbbd8,0,0
4339,794fcc425f074a1392206ed925fdbbd8,6dd2cbf4c24b4caeb625035869bca7b5,aa581aac963a4fad848ac11fe66e8637,human.pedestrian.adult,"[373.324, 1130.652, 1.067]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],b964464ea45d4e9493f324ba8d2a82a3,3b24f083c0bf42d695a1040efdab7ffe,0,0
4440,3b24f083c0bf42d695a1040efdab7ffe,6dd2cbf4c24b4caeb625035869bca7b5,67e5f88901214f3aa03d68e028185e22,human.pedestrian.adult,"[373.337, 1130.661, 1.095]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],794fcc425f074a1392206ed925fdbbd8,93d5b79041c64693a5b32f1103a39a06,0,0
4535,93d5b79041c64693a5b32f1103a39a06,6dd2cbf4c24b4caeb625035869bca7b5,29e056fc277543c9bc42310b122c640e,human.pedestrian.adult,"[373.35, 1130.67, 1.123]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",1,[4d8821270b4a47e3a8a300cbec48188e],3b24f083c0bf42d695a1040efdab7ffe,8bb63134d48840aaa2993f490855ff0d,2,0
4622,8bb63134d48840aaa2993f490855ff0d,6dd2cbf4c24b4caeb625035869bca7b5,ed5fc18c31904f96a8f0dbb99ff069c0,human.pedestrian.adult,"[373.363, 1130.678, 1.15]","[0.621, 0.669, 1.642]","[0.9831098797903927, 0.0, 0.0, -0.183016295062...",3,[4d8821270b4a47e3a8a300cbec48188e],93d5b79041c64693a5b32f1103a39a06,,1,0

In [ ]:
print("Instance token:", instance_token)
print("Number of observations:", len(one_instance))

Instance token: 6dd2cbf4c24b4caeb625035869bca7b5
Number of observations: 39

In [ ]:
instance_token = annotation_df["instance_token"].iloc[0]

one_instance = annotation_df[
    annotation_df["instance_token"] == instance_token
]

print("Instance token:", instance_token)
print("Number of observations:", len(one_instance))

Instance token: 6dd2cbf4c24b4caeb625035869bca7b5
Number of observations: 39

In [ ]:
positions = one_instance[
    [
        "sample_token",
        "translation"
    ]
]

positions

                          sample_token                 translation
0     ca9a282c9e77460f8360f564131a8af5    [373.256, 1130.419, 0.8]
69    39586f9d59004284a7114a68825e8eec   [373.256, 1130.419, 0.81]
147   356d81f38dd9473ba590f39e266f54e5   [373.256, 1130.419, 0.82]
233   e0845f5322254dafadbbed75aaa07969   [373.256, 1130.419, 0.83]
327   c923fe08b2ff4e27975d2bf30934383b   [373.256, 1130.419, 0.84]
430   f1e3d9d08f044c439ce86a2d6fcca57b  [373.256, 1130.419, 0.792]
533   4f545737bf3347fbbc9af60b0be9a963  [373.256, 1130.419, 0.744]
643   7626dde27d604ac28a0240bdd54eba7a  [373.256, 1130.419, 0.695]
761   be99ffc878b24aca8956bbb4e0f97d0c  [373.256, 1130.419, 0.647]
881   9813c23a5f1448b09bb7910fea9baf20  [373.256, 1130.419, 0.599]
1005  023c4df2d451409881d8e6ea82f14704   [373.256, 1130.419, 0.55]
1132  c235638ed66145988d17f9d0601923f2   [373.256, 1130.419, 0.75]
1261  bc3c8a953f6b4dcdb77b521d89f3d9d5   [373.256, 1130.419, 0.95]
1397  1e3d79dae62742a0ad64c91679863358    [373.256, 1130.419, 1.0]
1534  2afb9d32310e4546a71cbe432911eca2   [373.256, 1130.419, 1.15]
1675  cd21dbfc3bd749c7b10a5c42562e0c42    [373.214, 1130.48, 1.25]
1818  88449a5cb1644a199c1c11f6ac034867   [373.183, 1130.419, 1.25]
1965  2ff86dc19c4644a1a88ce5ba848f56e5   [373.152, 1130.357, 1.25]
2113  bf2938e43c6f487497cda76b51bfc406   [373.18, 1130.431, 1.263]
2265  b26e791522294bec90f86fd72226e35c  [373.208, 1130.504, 1.275]
2421  c844bf5a9f2243ff8f4bf2c85fe218ff  [373.237, 1130.577, 1.288]
2575  fedfb3a6cb804635a0f47143f9ca8d6f      [373.245, 1130.6, 1.3]
2726  965f6af5a92449348409029a5f048a38     [373.245, 1130.6, 1.25]
2874  4711bcd34644420da8bc77163431888e      [373.245, 1130.6, 1.2]
3018  a34fabc7aa674713b71f98ec541eb2d4     [373.245, 1130.6, 1.15]
3154  c78067571d104caba7c568a847d56971      [373.245, 1130.6, 1.1]
3279  4246e57f018745c9b2bc68feb3d71b58     [373.245, 1130.6, 1.05]
3401  a7acb150914b40bdad9a2dc4e657cbf9      [373.245, 1130.6, 1.0]
3523  0cd661df01aa40c3bb3a773ba86f753a     [373.245, 1130.6, 0.95]
3646  378a3a3e9af346308ab9dff8ced46d9c      [373.245, 1130.6, 0.9]
3771  eef55c3b48f34d949959b45130ee293a  [373.258, 1130.608, 0.928]
3890  5fda58ee3ae44ab9b4bbac7a2de66c27  [373.271, 1130.617, 0.956]
4006  919e3c4cec934168a3152077a9adcbea  [373.285, 1130.626, 0.984]
4119  b73152cab88f49d9ba195da81fde1809  [373.298, 1130.635, 1.012]
4232  6aa6fa91e0d1492e812eb7e57c47df6e  [373.311, 1130.643, 1.039]
4339  aa581aac963a4fad848ac11fe66e8637  [373.324, 1130.652, 1.067]
4440  67e5f88901214f3aa03d68e028185e22  [373.337, 1130.661, 1.095]
4535  29e056fc277543c9bc42310b122c640e    [373.35, 1130.67, 1.123]
4622  ed5fc18c31904f96a8f0dbb99ff069c0   [373.363, 1130.678, 1.15]

In [ ]:
one_instance = one_instance.copy()

one_instance[["x", "y", "z"]] = pd.DataFrame(
    one_instance["translation"].tolist(),
    index=one_instance.index
)

NameError: name 'one_instance' is not defined

In [ ]:
one_instance[
    [
        "sample_token",
        "x",
        "y",
        "z"
    ]
]

                          sample_token        x         y      z
0     ca9a282c9e77460f8360f564131a8af5  373.256  1130.419  0.800
69    39586f9d59004284a7114a68825e8eec  373.256  1130.419  0.810
147   356d81f38dd9473ba590f39e266f54e5  373.256  1130.419  0.820
233   e0845f5322254dafadbbed75aaa07969  373.256  1130.419  0.830
327   c923fe08b2ff4e27975d2bf30934383b  373.256  1130.419  0.840
430   f1e3d9d08f044c439ce86a2d6fcca57b  373.256  1130.419  0.792
533   4f545737bf3347fbbc9af60b0be9a963  373.256  1130.419  0.744
643   7626dde27d604ac28a0240bdd54eba7a  373.256  1130.419  0.695
761   be99ffc878b24aca8956bbb4e0f97d0c  373.256  1130.419  0.647
881   9813c23a5f1448b09bb7910fea9baf20  373.256  1130.419  0.599
1005  023c4df2d451409881d8e6ea82f14704  373.256  1130.419  0.550
1132  c235638ed66145988d17f9d0601923f2  373.256  1130.419  0.750
1261  bc3c8a953f6b4dcdb77b521d89f3d9d5  373.256  1130.419  0.950
1397  1e3d79dae62742a0ad64c91679863358  373.256  1130.419  1.000
1534  2afb9d32310e4546a71cbe432911eca2  373.256  1130.419  1.150
1675  cd21dbfc3bd749c7b10a5c42562e0c42  373.214  1130.480  1.250
1818  88449a5cb1644a199c1c11f6ac034867  373.183  1130.419  1.250
1965  2ff86dc19c4644a1a88ce5ba848f56e5  373.152  1130.357  1.250
2113  bf2938e43c6f487497cda76b51bfc406  373.180  1130.431  1.263
2265  b26e791522294bec90f86fd72226e35c  373.208  1130.504  1.275
2421  c844bf5a9f2243ff8f4bf2c85fe218ff  373.237  1130.577  1.288
2575  fedfb3a6cb804635a0f47143f9ca8d6f  373.245  1130.600  1.300
2726  965f6af5a92449348409029a5f048a38  373.245  1130.600  1.250
2874  4711bcd34644420da8bc77163431888e  373.245  1130.600  1.200
3018  a34fabc7aa674713b71f98ec541eb2d4  373.245  1130.600  1.150
3154  c78067571d104caba7c568a847d56971  373.245  1130.600  1.100
3279  4246e57f018745c9b2bc68feb3d71b58  373.245  1130.600  1.050
3401  a7acb150914b40bdad9a2dc4e657cbf9  373.245  1130.600  1.000
3523  0cd661df01aa40c3bb3a773ba86f753a  373.245  1130.600  0.950
3646  378a3a3e9af346308ab9dff8ced46d9c  373.245  1130.600  0.900
3771  eef55c3b48f34d949959b45130ee293a  373.258  1130.608  0.928
3890  5fda58ee3ae44ab9b4bbac7a2de66c27  373.271  1130.617  0.956
4006  919e3c4cec934168a3152077a9adcbea  373.285  1130.626  0.984
4119  b73152cab88f49d9ba195da81fde1809  373.298  1130.635  1.012
4232  6aa6fa91e0d1492e812eb7e57c47df6e  373.311  1130.643  1.039
4339  aa581aac963a4fad848ac11fe66e8637  373.324  1130.652  1.067
4440  67e5f88901214f3aa03d68e028185e22  373.337  1130.661  1.095
4535  29e056fc277543c9bc42310b122c640e  373.350  1130.670  1.123
4622  ed5fc18c31904f96a8f0dbb99ff069c0  373.363  1130.678  1.150

In [ ]:
sample_token = one_instance.iloc[0]["sample_token"]

sample = nusc.get(
    "sample",
    sample_token
)

sample["data"]

NameError: name 'one_instance' is not defined

In [ ]:
observation = one_instance.iloc[0]

sample_token = observation["sample_token"]

print("Sample token:", sample_token)

Sample token: ca9a282c9e77460f8360f564131a8af5

In [ ]:
sample = nusc.get(
    "sample",
    sample_token
)

NameError: name 'nusc' is not defined

In [ ]:
sample["data"]

{'RADAR_FRONT': '37091c75b9704e0daa829ba56dfa0906',
 'RADAR_FRONT_LEFT': '11946c1461d14016a322916157da3c7d',
 'RADAR_FRONT_RIGHT': '491209956ee3435a9ec173dad3aaf58b',
 'RADAR_BACK_LEFT': '312aa38d0e3e4f01b3124c523e6f9776',
 'RADAR_BACK_RIGHT': '07b30d5eb6104e79be58eadf94382bc1',
 'LIDAR_TOP': '9d9bf11fb0e144c8b446d54a8a00184f',
 'CAM_FRONT': 'e3d495d4ac534d54b321f50006683844',
 'CAM_FRONT_RIGHT': 'aac7867ebf4f446395d29fbd60b63b3b',
 'CAM_BACK_RIGHT': '79dbb4460a6b40f49f9c150cb118247e',
 'CAM_BACK': '03bea5763f0f4722933508d5999c5fd8',
 'CAM_BACK_LEFT': '43893a033f9c46d4a51b5e08a67a1eb7',
 'CAM_FRONT_LEFT': 'fe5422747a7d4268a4b07fc396707b23'}

In [ ]:
camera_name = "CAM_FRONT"

cam_token = sample["data"][camera_name]

print("Camera token:", cam_token)

Camera token: e3d495d4ac534d54b321f50006683844

In [ ]:
sample_data = nusc.get(
    "sample_data",
    cam_token
)

sample_data

{'token': 'e3d495d4ac534d54b321f50006683844',
 'sample_token': 'ca9a282c9e77460f8360f564131a8af5',
 'ego_pose_token': 'e3d495d4ac534d54b321f50006683844',
 'calibrated_sensor_token': '1d31c729b073425e8e0202c5c6e66ee1',
 'timestamp': 1532402927612460,
 'fileformat': 'jpg',
 'is_key_frame': True,
 'height': 900,
 'width': 1600,
 'filename': 'samples/CAM_FRONT/n015-2018-07-24-11-22-45+0800__CAM_FRONT__1532402927612460.jpg',
 'prev': '',
 'next': '68e8e98cf7b0487baa139df808641db7',
 'sensor_modality': 'camera',
 'channel': 'CAM_FRONT'}

In [ ]:
calibrated_sensor = nusc.get(
    "calibrated_sensor",
    sample_data["calibrated_sensor_token"]
)

In [ ]:
calibrated_sensor

{'token': '1d31c729b073425e8e0202c5c6e66ee1',
 'sensor_token': '725903f5b62f56118f4094b46a4470d8',
 'translation': [1.70079118954, 0.0159456324149, 1.51095763913],
 'rotation': [0.4998015430569128,
  -0.5030316162024876,
  0.4997798114386805,
  -0.49737083824542755],
 'camera_intrinsic': [[1266.417203046554, 0.0, 816.2670197447984],
  [0.0, 1266.417203046554, 491.50706579294757],
  [0.0, 0.0, 1.0]]}

In [ ]:
calibrated_sensor["camera_intrinsic"]

[[1266.417203046554, 0.0, 816.2670197447984],
 [0.0, 1266.417203046554, 491.50706579294757],
 [0.0, 0.0, 1.0]]

In [ ]:
ego_pose = nusc.get(
    "ego_pose",
    sample_data["ego_pose_token"]
)

In [ ]:
ego_pose

{'token': 'e3d495d4ac534d54b321f50006683844',
 'timestamp': 1532402927612460,
 'rotation': [0.5720063498929273,
  -0.0021434844534272707,
  0.011564094980151613,
  -0.8201648693182716],
 'translation': [411.4199861830012, 1181.197175631848, 0.0]}

In [ ]:
observation = one_instance.iloc[0]

sample_token = observation["sample_token"]

sample = nusc.get(
    "sample",
    sample_token
)

camera_name = "CAM_FRONT"

cam_token = sample["data"][camera_name]

sample_data = nusc.get(
    "sample_data",
    cam_token
)

calibrated_sensor = nusc.get(
    "calibrated_sensor",
    sample_data["calibrated_sensor_token"]
)

ego_pose = nusc.get(
    "ego_pose",
    sample_data["ego_pose_token"]
)

NameError: name 'one_instance' is not defined

In [40]:
print("Object translation:")
print(observation["translation"])

print("\nCamera image:")
print(sample_data["filename"])

print("\nImage size:")
print(sample_data["width"], sample_data["height"])

print("\nCamera intrinsic:")
print(calibrated_sensor["camera_intrinsic"])

print("\nCamera calibration translation:")
print(calibrated_sensor["translation"])

print("\nEgo pose translation:")
print(ego_pose["translation"])

Object translation:

NameError: name 'observation' is not defined

In [38]:
import numpy as np

from pyquaternion import Quaternion

In [39]:
observation = one_instance.iloc[0]

NameError: name 'one_instance' is not defined

In [36]:
point_global = np.array(
    observation["translation"]
)

print(point_global)

NameError: name 'np' is not defined